### ISSUE TITLE
Unable to open debugger port: java.io.IOException "handshake failed - connection prematurally closed

### ISSUE THREAD

**Issue by NathanPB** [thundra-io/thundra-intellij-issues#3]
Hello, I didn't know exactly where I should open this issue and also couldn't find a support page, so I'm opening this here.

I'm using the IntelliJ plugin (Debugger for AWS Lambda) version 1.4 along with IntelliJ IDEA Ultimate 2021.2, I have set up all the steps needed to use the Thundra debugger with NodeJS, Serverless and IDEA, including the authkey, apikey, Serverless plugin and the ``@thundra/core`` package (``serverless@2.66``, ``@thundra/core@2.13.27``, ``serverless-plugin-thundra@2.5.9``).

I run the Thundra configuration as debug and set a breakpoint in my handler, but nothing happens when this breakpoint should be hit. Also, after a few instants, the debugger crashes with a ``handshake failed - connection prematurally closed`` message.

The in the dashboard at https://thundra.apm.io everything seems to be working just fine, I can inspect my functions there and everything, but the IDE's debugger just won't work. I also tried the VSCode extension, the exact same thing happens.

I'm using Arch with the ``5.15.7-arch-1`` kernel version, I don't know which other information I should include in order for this issue to be investigated. Furthermore, I will attach my IntelliJ IDEA logs to this issue.

Thanks for your attention

[idea.log](https://github.com/thundra-io/thundra-intellij-issues/files/8091176/idea.log)

**Comment by suleymanbarman** [comment]
Hi Nathan, you are exactly the right place to open issue for Thundra Intellij Debugger for Lambda but we need to understand your case whether it is related to an issue or setup config. Could you join our slack to let us understand the case?
https://thundra-community.slack.com/

**Comment by suleymanbarman** [comment]
And also you can join our slack to let us understand your case properly.

https://thundra-community.slack.com/

**Comment by NathanPB** [comment]
I'm not very familiarized with this ecosystem yet, but the lambdas are in VPC groups. Are there additional steps that I need to do? I will join the Slack channel in a few moments

**Comment by rwxdash** [comment]
Hi @NathanPB, before we go any further I think the main issue is that you're using our IntelliJ plugin on a NodeJS lambda. 

The IntelliJ plugin is currently only for Java runtimes. For NodeJS lambdas, we recommend using our VSCode plugin or if you want to stay in the Jetbrains ecosystem, Webstorm. 

For the Webstorm use case, since we don't have any plugins there, you have to use our debug client on your machine. Further instructions on this matter can be found here: https://apm.docs.thundra.io/ide-integrations/others

Theoretically, you can use the debug client with IntelliJ as well. However, if you are using TypeScript or some sort of bundling, Webstorm is usually clever enough to figure the paths on its own.

If you are in our Slack community channel, we can help you onboard with our Lambda debugger and give quick support to resolve your issues on a private channel.

**Comment by NathanPB** [comment]
Very sad to hear that the IntelliJ plugin is only for java runtimes :(

I will try again and reopen this issue in the VSCode plugin repository if it doesn't work there.

Is the IntelliJ plugin open source somewhere? We could try to make it work with other runtimes too, since IntelliJ Ultimate is kind of an all-in-one IDE

**Comment by rwxdash** [comment]
Unfortunately, the code for the IntelliJ plugin isn't public at the moment but it's certainly on our roadmap.
